baseURL = 'https://riley.sh/'
languageCode = 'en-us'
title = "Riley Shuping's Machinations"
theme   = "simple-tex"
[params]
mainSections = ["posts"]
[menu]
  [[menu.main]]
    name = "Posts"
    url  = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2
[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = true
    lineNos = false